Added Heroku stuff.
mustachioed-meerkats/mustachioed-meerkats pull request #27
Opened 2017-09-01 22:24 UTC by Sam0064

Added Heroku settings to the repo. Heroku should now be buildable from any of our machines.

2017-09-02 03:43 UTC, lazdinst approved these changes
Approved.

2017-09-02 08:03 UTC, kevinzhuang10 requested changes
Please update PR with Waffle tickets.

2017-09-02 18:13 UTC, kevinzhuang10 approved these changes

2017-09-02 18:15 UTC, merged

2017-09-05 22:14 UTC, olegtrofimov1 commented on package.json
> +    "test": " mocha ./server --recursive  jest --testPathPattern ./client/test\/.js  NODE_ENV=test grunt test",
Wait this is starting the mocha server, then running jest and then running grunt test? Why don't you do all of this in grunt? And simply run NODE_ENV=test grunt test